### ISSUE TITLE
Error: no Auth Provider found for name "gcp" when executed against GKE clusters

### ISSUE THREAD

**Issue by minhnhupham** [signalfx/kubectl-splunk#31]
Currently when running:
`kubectl-splunk support` against our GKE clusters, 
we get the following errors:
**Error: no Auth Provider found for name "gcp"**

The plugin/binary does not seem to pick up the kubeconfig context and appears to fail to authenticate.

kubeclt-splunk version: 0.3.0
kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.900", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-03-30T09:37:00Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by atoulme** [comment]
This repository is not actively supported. Please open a support case if you require attention to this issue.
